version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deardays
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d deardays"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build: ./backend
    env_file: .env
    ports: ["8080:8080"]
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE: http://localhost:8080/api
    ports: ["5173:5173"]
    depends_on: [backend]